name: Regression

on:
  workflow_dispatch:
    inputs:
      hardware_config:
        description: 'Hardware Configuration ID(s), comma separated'
        required: true
        default: '1,2,3'


jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install mysql-connector-python
      - run: python ./.github/scripts/regression.py
        env:
          HW_CONFIG: ${{ inputs.hardware_config }}
          CI_DB_HOSTNAME: ${{ secrets.CI_DB_HOSTNAME }}
          CI_DB_PORT: ${{ secrets.CI_DB_PORT }}
          CI_DB_USERNAME: ${{ secrets.CI_DB_USERNAME }}
          CI_DB_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
