name: Regression

on:
  workflow_dispatch:
    inputs:
      hardware_config:
        description: 'Hardware Configuration(s), comma separated'
        required: true
        default: 'RTX4090'


jobs:
  print_hw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ inputs.hardware_config }}"
          echo "$HW_CONFIG 2"
        env:
          HW_CONFIG: ${{ inputs.hardware_config }}
      - run: pip install mysql-connector-python
      - run: python ./scripts/regression/regression.py
        env:
          CI_DB_HOSTNAME: ${{ secrets.CI_DB_HOSTNAME }}
          CI_DB_PORT: ${{ secrets.CI_DB_PORT }}
          CI_DB_USERNAME: ${{ secrets.CI_DB_USERNAME }}
          CI_DB_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
